version: "3.8"

services:
  lint:
    build:
      target: dev
    working_dir: /app
    command:
      - sh
      - -ec
      - |
        flake8 .
        black --check --verbose .
    volumes:
      - .:/app

  test:
    build:
      target: dev
    working_dir: /app
    command: pytest -cov
    volumes:
      - .:/app

  app:
    build:
      target: prod
    stdin_open: true
    tty: true
    working_dir: /app
    command: python -m toy_robot.main
    volumes:
      - .:/app
