version: "3.8"

services:
  test:
    build:
      target: dev
    working_dir: /app
    command:
      - sh
      - -ec
      - |
        pytest -cov
        flake8 .
        black --check .
    volumes:
      - .:/app

  app:
    build:
      target: prod
    stdin_open: true
    tty: true
    working_dir: /app
    command: python -m toy_robot.main
    volumes:
      - .:/app
