name: Test
on: [push]
jobs:
  test:
    name: Test
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install poetry==1.1.15
          poetry config virtualenvs.create false
          poetry export -f requirements.txt --dev | pip install -r /dev/stdin
      - name: Build docker images
        run: docker compose build
      - name: Run lint
        run: docker compose run test
      - name: Run tests
        run: docker compose run test
